apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blue-green-demo-vsvc-active
spec:
  gateways:
  - rollouts-demo-gateway
  hosts:
  - 'blue-green.example'
  http:
  - name: active
    route:
    - destination:
        host: bluegreen-demo.argo-rollout-demo.svc.cluster.local
        port:
          number: 80
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: blue-green-demo-vsvc-preview
spec:
  gateways:
  - rollouts-demo-gateway
  hosts:
  - 'blue-green-preview.example'
  http:
  - name: preview
    route:
    - destination:
        host: bluegreen-demo-preview.argo-rollout-demo.svc.cluster.local
        port:
          number: 80

