apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-appset-generator
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'appset-generator'
    spec:
      project: resource-hook
      source:
        repoURL: https://github.com/serhatYilmazz/ArgoCD
        targetRevision: HEAD
        path: main
      destination:
        server: '{{url}}'
        namespace: resource-hook
