apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
spec:
  destination:
    name: ''
    namespace: argo-demo
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/serhatYilmazz/ArgoCD'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
