apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-example-deployment
  labels:
    app: argocd-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd-example
  template:
    metadata:
      labels:
        app: argocd-example
    spec:
      containers:
        - name: nginx:stable
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - mountPath: /app
              name: cm
      volumes:
        - name: cm
          configMap:
            name: argocd-example-configmap

