apiVersion: v1
kind: Service
metadata:
  name: argocd-example-service
  labels:
    app: argocd-example
spec:
  selector:
    app: argocd-example
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP


