apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argocd
spec:
  generators:
  # - list:
  #     elements:
  #     - cluster: stage
  #       url: https://kubernetes.default.svc
  #     - cluster: prod
  #       url: https://kubernetes.default.svc
  # generators:
   
  #   - git:
  #       repoURL: https://github.com/serhatYilmazz/ArgoCD
  #       revision: HEAD
  #       files:
  #       - path: "main/cluster-config/**/config.json"
  # template:
  #   metadata:
  #     name: '{{cluster.env}}-nginx'
  #   spec:
  #     project: default
  #     source:
  #       repoURL: https://github.com/serhatYilmazz/ArgoCD
  #       targetRevision: HEAD
  #       path: main/nginx-{{cluster.env}}
  #     destination:
  #       server: '{{url}}'
    - git:
        repoURL: https://github.com/serhatYilmazz/ArgoCD
        revision: HEAD
        files:
        - path: "main/rollouts/applications/config.json"
  template:
    metadata:
      name: '{{app.name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/serhatYilmazz/ArgoCD
        targetRevision: HEAD
        path: '{{app.path}}'
      destination:
        server: '{{url}}'
        namespace: rollouts-demo
