apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.2/manifests/install.yaml
  - rollout-install.yml

components:
  - https://github.com/argoproj-labs/argocd-extensions/manifests