apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollouts-demo-vsvc
spec:
  gateways:
  - rollouts-demo-gateway
  hosts:
  - 'canary.example'
  http:
  - name: primary
    route:
    - destination:
        host: rollouts-demo-stable.argo-rollout-demo.svc.cluster.local
        port:
          number: 80
      weight: 100
    - destination:
        host: rollouts-demo-canary.argo-rollout-demo.svc.cluster.local
        port:
          number: 80
      weight: 0