apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-cron-w
spec:
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: whalesay
    templates:
    - name: whalesay
      steps:
      - - name: hello
          template: whalesay    # We reference our second "template" here
          arguments:
            parameters: [{name: message, value: "hello1"}]
      - - name: hello-1
          template: whalesay    # We reference our second "template" here
          arguments:
            parameters: [{name: message, value: "hello1"}]
      - - name: hello-2
          template: whalesay    # We reference our second "template" here
          arguments:
            parameters: [{name: message, value: "hello1"}]
    - name: whalesay             # The second "template" in this Workflow, it is referenced by "hello"
    inputs:
      parameters:
      - name: message
    container:                # The type of this "template" is "container"
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]