apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
nameSuffix: -dev
resources:
  - ../base
  - resource-post-sync-hook.yml
  - resource-sync-hook.yml
  - resource-pre-sync-hook.yml
