apiVersion: batch/v1
kind: Job
metadata:
  name: app-slack-notification-dev-post
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "payload={\"channel\": \"#somechannel\", \"username\": \"hello\", \"text\": \"nginx-dev App Sync succeeded\", \"icon_emoji\": \":ghost:\"}"
          - "https://hooks.slack.com/services/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"
      restartPolicy: Never
  backoffLimit: 2